/**
 * Onchain feature constants
 * All features use Reown Wallet for secure wallet connections
 */

export const ONCHAIN_FEATURES = {
  TRANSFER: 'token-transfer',
  APPROVAL: 'token-approval',
  NFT_MINT: 'nft-mint',
  STAKE: 'stake',
  UNSTAKE: 'unstake',
  BRIDGE: 'bridge',
  SWAP: 'swap',
  ADD_LIQUIDITY: 'add-liquidity',
  REMOVE_LIQUIDITY: 'remove-liquidity',
  CLAIM_REWARDS: 'claim-rewards',
  VOTE: 'vote',
  DELEGATE: 'delegate',
  WRAP_UNWRAP: 'wrap-unwrap',
  SET_ENS: 'set-ens',
  BATCH: 'batch-transaction',
  CANCEL_TX: 'cancel-transaction',
  SPEED_UP_TX: 'speed-up-transaction',
  SIGN_MESSAGE: 'sign-message',
  SIGN_TYPED_DATA: 'sign-typed-data',
  MULTISIG: 'multisig',
  BALANCE: 'token-balance',
  TX_HISTORY: 'transaction-history',
  GAS_ESTIMATE: 'gas-estimation',
  TOKEN_METADATA: 'token-metadata',
  NFT_BALANCE: 'nft-balance',
  NFT_TRANSFER: 'nft-transfer',
  NFT_APPROVAL: 'nft-approval',
  LP_POSITION: 'lp-position',
  STAKING_POSITION: 'staking-position',
  TOKEN_PRICE: 'token-price',
  CONTRACT_READ: 'contract-read',
  EVENT_LISTENING: 'event-listening',
  TOKEN_ALLOWANCE: 'token-allowance',
  NONCE: 'nonce',
  GAS_PRICE: 'gas-price',
  BLOCK_NUMBER: 'block-number',
  TX_STATUS: 'transaction-status',
  CONTRACT_VERIFICATION: 'contract-verification',
  TOKEN_LIST: 'token-list',
  CHAIN_STATE: 'chain-state',
  TOKEN_SLIPPAGE: 'token-slippage',
  TOKEN_LIQUIDITY_DEPTH: 'token-liquidity-depth',
  TOKEN_TRADING_VOLUME: 'token-trading-volume',
  TOKEN_HOLDER_ACTIVITY: 'token-holder-activity',
  TOKEN_BURN_RATE: 'token-burn-rate',
  TOKEN_MINT_RATE: 'token-mint-rate',
  TOKEN_INFLATION: 'token-inflation',
  TOKEN_DEFLATION: 'token-deflation',
  TOKEN_HOLDER_RETENTION: 'token-holder-retention',
  TOKEN_TRANSFER_VELOCITY: 'token-transfer-velocity',
  TOKEN_CONCENTRATION_RISK: 'token-concentration-risk',
  TOKEN_MARKET_DEPTH: 'token-market-depth',
  TOKEN_ORDER_BOOK: 'token-order-book',
  TOKEN_SWAP_AGGREGATOR: 'token-swap-aggregator',
  TOKEN_YIELD_OPTIMIZER: 'token-yield-optimizer',
  TOKEN_REBALANCER: 'token-rebalancer',
  TOKEN_PORTFOLIO_OPTIMIZER: 'token-portfolio-optimizer',
  TOKEN_RISK_CALCULATOR: 'token-risk-calculator',
  TOKEN_CORRELATION: 'token-correlation',
  TOKEN_PERFORMANCE: 'token-performance',
  TOKEN_TREND_ANALYZER: 'token-trend-analyzer',
  TOKEN_SUPPORT_RESISTANCE: 'token-support-resistance',
  TOKEN_VOLUME_PROFILE: 'token-volume-profile',
  TOKEN_MARKET_MAKER: 'token-market-maker',
  TOKEN_ARBITRAGE: 'token-arbitrage',
  TOKEN_FLASH_SWAP: 'token-flash-swap',
  TOKEN_IMPERMANENT_LOSS: 'token-impermanent-loss',
  TOKEN_APR_APY: 'token-apr-apy',
  TOKEN_REWARD_TRACKER: 'token-reward-tracker',
  TOKEN_GOVERNANCE_PROPOSAL: 'token-governance-proposal',
  TOKEN_TREASURY_TRACKER: 'token-treasury-tracker',
  TOKEN_RESERVE_TRACKER: 'token-reserve-tracker',
  TOKEN_BACKING_CALCULATOR: 'token-backing-calculator',
  TOKEN_COLLATERAL_RATIO: 'token-collateral-ratio',
  TOKEN_LIQUIDATION_THRESHOLD: 'token-liquidation-threshold',
  TOKEN_HEALTH_FACTOR: 'token-health-factor',
  TOKEN_BORROW_RATE: 'token-borrow-rate',
  TOKEN_SUPPLY_RATE: 'token-supply-rate',
  TOKEN_UTILIZATION_RATE: 'token-utilization-rate',
  TOKEN_PROTOCOL_REVENUE: 'token-protocol-revenue',
  TOKEN_PROTOCOL_FEES: 'token-protocol-fees',
  TOKEN_GOVERNANCE_TREASURY: 'token-governance-treasury',
  TOKEN_PROPOSAL_VOTING: 'token-proposal-voting',
  TOKEN_QUORUM_TRACKER: 'token-quorum-tracker',
  TOKEN_VOTING_PERIOD: 'token-voting-period',
  TOKEN_EXECUTION_TRACKER: 'token-execution-tracker',
  TOKEN_TIMELOCK_TRACKER: 'token-timelock-tracker',
  TOKEN_MULTISIG_TRACKER: 'token-multisig-tracker',
  TOKEN_PROXY_ADMIN: 'token-proxy-admin',
  TOKEN_IMPLEMENTATION: 'token-implementation',
  TOKEN_STORAGE_SLOT: 'token-storage-slot',
  TOKEN_EVENT_PARSER: 'token-event-parser',
  TOKEN_TX_DECODER: 'token-tx-decoder',
  TOKEN_ABI_GENERATOR: 'token-abi-generator',
  TOKEN_INTERFACE_DETECTOR: 'token-interface-detector',
  TOKEN_STANDARD_DETECTOR: 'token-standard-detector',
  TOKEN_COMPATIBILITY: 'token-compatibility',
} as const;

export const SUPPORTED_CHAINS = {
  ETHEREUM: 1,
  BASE: 8453,
  ARBITRUM: 42161,
  OPTIMISM: 10,
  POLYGON: 137,
  ZKSYNC: 324,
} as const;

export const REOWN_WALLET_REQUIRED = 'All onchain features require Reown Wallet connection';

